export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'

export const UPDATE_CATEGORIES_REQUEST = 'UPDATE_CATEGORIES_REQUEST'
export const UPDATE_CATEGORIES_FAILURE = 'UPDATE_CATEGORIES_FAILURE'
export const UPDATE_CATEGORIES_SUCCESS = 'UPDATE_CATEGORIES_SUCCESS'

export const DELETE_CATEGORIES_REQUEST = 'DELETE_CATEGORIES_REQUEST'
export const DELETE_CATEGORIES_FAILURE = 'DELETE_CATEGORIES_FAILURE'
export const DELETE_CATEGORIES_SUCCESS = 'DELETE_CATEGORIES_SUCCESS'

export const ADD_CATEGORIES_REQUEST = 'ADD_CATEGORIES_REQUEST'
export const ADD_CATEGORIES_FAILURE = 'ADD_CATEGORIES_FAILURE'
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS'





export const FETCH_RECIPIENTS_REQUEST = 'FETCH_RECIPIENTS_REQUEST'
export const FETCH_RECIPIENTS_FAILURE = 'FETCH_RECIPIENTS_FAILURE'
export const FETCH_RECIPIENTS_SUCCESS = 'FETCH_RECIPIENTS_SUCCESS'

export const ADD_RECIPIENTS_REQUEST = 'ADD_RECIPIENTS_REQUEST'
export const ADD_RECIPIENTS_FAILURE = 'ADD_RECIPIENTS_FAILURE'
export const ADD_RECIPIENTS_SUCCESS = 'ADD_RECIPIENTS_SUCCESS'

export const UPDATE_RECIPIENTS_REQUEST = 'UPDATE_RECIPIENTS_REQUEST'
export const UPDATE_RECIPIENTS_FAILURE = 'UPDATE_RECIPIENTS_FAILURE'
export const UPDATE_RECIPIENTS_SUCCESS = 'UPDATE_RECIPIENTS_SUCCESS'

export const DELETE_RECIPIENTS_REQUEST = 'DELETE_RECIPIENTS_REQUEST'
export const DELETE_RECIPIENTS_FAILURE = 'DELETE_RECIPIENTS_FAILURE'
export const DELETE_RECIPIENTS_SUCCESS = 'DELETE_RECIPIENTS_SUCCESS'





export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST'
export const UPDATE_TRANSACTION_FAILURE = 'UPDATE_TRANSACTION_FAILURE'
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS'

export const ADD_TRANSACTION_REQUEST = 'ADD_TRANSACTION_REQUEST'
export const ADD_TRANSACTION_FAILURE = 'ADD_TRANSACTION_FAILURE'
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS'

export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST'
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE'
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS'

export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST'
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTIONS_FAILURE'
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS'


export const FETCH_CURRENT_MONTH_MONEY_REQUEST = 'FETCH_CURRENT_MONTH_MONEY_REQUEST'
export const FETCH_CURRENT_MONTH_MONEY_FAILURE = 'FETCH_CURRENT_MONTH_MONEY_FAILURE'
export const FETCH_CURRENT_MONTH_MONEY_SUCCESS = 'FETCH_CURRENT_MONTH_MONEY_SUCCESS'



export const FETCH_RECURRING_PAYMENTS_REQUEST = 'FETCH_RECURRING_PAYMENTS_REQUEST'
export const FETCH_RECURRING_PAYMENTS_FAILURE = 'FETCH_RECURRING_PAYMENTS_FAILURE'
export const FETCH_RECURRING_PAYMENTS_SUCCESS = 'FETCH_RECURRING_PAYMENTS_SUCCESS'

export const ADD_RECURRING_PAYMENT_REQUEST = 'ADD_RECURRING_PAYMENT_REQUEST'
export const ADD_RECURRING_PAYMENT_FAILURE = 'ADD_RECURRING_PAYMENT_FAILURE'
export const ADD_RECURRING_PAYMENT_SUCCESS = 'ADD_RECURRING_PAYMENT_SUCCESS'

export const UPDATE_RECURRING_PAYMENT_REQUEST = 'UPDATE_RECURRING_PAYMENT_REQUEST'
export const UPDATE_RECURRING_PAYMENT_FAILURE = 'UPDATE_RECURRING_PAYMENT_FAILURE'
export const UPDATE_RECURRING_PAYMENT_SUCCESS = 'UPDATE_RECURRING_PAYMENT_SUCCESS'

export const DELETE_RECURRING_PAYMENT_REQUEST = 'DELETE_RECURRING_PAYMENT_REQUEST'
export const DELETE_RECURRING_PAYMENT_FAILURE = 'DELETE_RECURRING_PAYMENT_FAILURE'
export const DELETE_RECURRING_PAYMENT_SUCCESS = 'DELETE_RECURRING_PAYMENT_SUCCESS'