export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'


export const FETCH_RECIPIENTS_REQUEST = 'FETCH_RECIPIENTS_REQUEST'
export const FETCH_RECIPIENTS_FAILURE = 'FETCH_RECIPIENTS_FAILURE'
export const FETCH_RECIPIENTS_SUCCESS = 'FETCH_RECIPIENTS_SUCCESS'